### ISSUE TITLE
Anmeldung (Parameter: Email, PW)

### ISSUE THREAD

**Issue by basti7** [ASE-Projekte-WS-2021/ase-ws-21-vp-manager#1]
Als Nutzer:in möchte ich mich über meine universitäre Email Adresse anmelden können, um geräteunabhängig auf meine Daten in der App zugreifen zu können.
! Dieser Issue wird durch #34 ersetzt !

**Comment by KilianBogner** [comment]
Dieser Issue wird ersetzt.
