### ISSUE TITLE
Design Schema

### ISSUE THREAD

**Issue by basti7** [ASE-Projekte-WS-2021/ase-ws-21-vp-manager#15]
Als Nutzer:in wünsche ich mir ein einheitliches Design der App, in Bezug auf Struktur und Gestaltung, um eine möglichst konsistente und angenehme Interaktion mit der Anwendung zu haben.
! Dieses Issue wird von #59 und #60 abgelöst !

**Comment by KilianBogner** [comment]
Dieses Issue wurde ersetzt.
