### ISSUE TITLE
Terminauswahl für einzelne Tage

### ISSUE THREAD

**Issue by Tokimetakaari** [ASE-Projekte-WS-2021/ase-ws-21-vp-manager#25]
Als Nutzer:in möchte ich alle Tage, an denen die Studienteilnahme möglich ist, in einem Kalender markieren können, damit es eine praktische Übersicht gibt und ich für all diese Tage die gleichen Termine erstellen kann.

**Comment by KilianBogner** [comment]
Issue wird erstmal nicht Implementiert.
