### ISSUE TITLE
Hinweis auf fehlende optionale Angaben bei Studienerstellung

### ISSUE THREAD

**Issue by Mutigo** [ASE-Projekte-WS-2021/ase-ws-21-vp-manager#37]
Als Nutzer:in möchte ich einen Hinweis erhalten, sollte ich ein optionale Angaben nicht eingetragen haben wie zum Beispiel Termine. Damit erhalte ich die Möglichkeit meine Angaben noch einmal zu überprüfen, ob diese meinen Anforderung entspricht.

**Comment by basti7** [comment]
merged into #37
