### ISSUE TITLE
Informationen zu anstehenden Terminen

### ISSUE THREAD

**Issue by Mutigo** [ASE-Projekte-WS-2021/ase-ws-21-vp-manager#7]
Als Nutzer:in der App möchte ich über anstehende Termine bezüglich meiner Studien informiert werden. Auf der Start/Home-Seite sollen mir Termine von Studien die ich anbiete, als auch von Studien an denen ich teilnehme, angezeigt werden.
! Dieses Issue wird durch #67 ersetzt !

**Comment by KilianBogner** [comment]
Dieses Issue ist ersetzt worden.
